%{

#include<stdio.h>
#include<stdlib.h>
#include<string.h>

#include "Lexical.l"

%}




//End of file
%token T_EOF			

//Identifier
%token T_IDENTIFIER		

//Constants
%token T_ICONST			
%token T_CCONST			
%token T_SCONST			

//Keywords - Program words
%token T_INTEGER   		
%token T_CHAR 			
%token T_STRING 		

%token T_IF        		
%token T_THEN      		
%token T_ELSE      		
%token T_ELSEIF    		
%token T_ENDIF			
%token T_FOR       		
%token T_TO        		
%token T_STEP      		
%token T_ENDFOR    		
%token T_WHILE     		
%token T_ENDWHILE  		
%token T_SWITCH    		
%token T_CASE      		
%token T_DEFAULT   		
%token T_ENDSWITCH 		

%token T_PROGRAM   		
%token T_FUNCTION  		
%token T_VARS      		
%token T_END_FUNCTION 	
%token T_RETURN    		
%token T_STARTMAIN 		
%token T_ENDMAIN   		

%token T_BREAK     		
%token T_PRINT     	

//Operators
%token T_ANDOP 			
%token T_OROP			
%token T_ADDOP			
%token T_MULOP			
%token T_POWOP			
%token T_FOROP			
%token T_EQUOP			
%token T_ASS			
%token T_COMPOP			

//Comment
%token T_COMM      		

//Othen tokens
%token T_SEMIC			
%token T_COLON			
%token T_BRA_OPEN		
%token T_BRA_CLOSE 		
%token T_AGG_OPEN		
%token T_AGG_CLOSE 		
%token T_COMMA 			




%%

OPERATOR:					T_ADDOP | T_MULLOP | T_POW

LOGICAL_OPERATOR:           T_ANDOP | T_OROP

//VAR_TYPE:					T_INTEGER | T_CHAR | T_STRING | STRUCT

//VAR_TYPES:                VAR_TYPE T_IDENTIFIER T_SEMIC "\n"| VAR_TYPES VAR_TYPE T_IDENTIFIER T_SEMIC "\n"

//VAR_ASS:					T_VARS "\n" VAR_TYPES 

//STRUCT: 					

VARIABLE:					T_ICONST | T_CCONST
VARIABLES: 					VARIABLE | VARIABLE T_COMMA VARIABLES

PROGRAM:					T_PROGRAM T_IDENTIFIER "\n" FUNCTIONS VAR_ASS MAIN | T_PROGRAM T_IDENTIFIER "\n" VAR_ASS MAIN

FUNCTION:					T_FUNCTION T_IDENTIFIER T_BRA_OPEN VARIABLES T_BRA_CLOSE "\n" FUNCTIONBODY T_ENDFUNCTION

FUNCTIONS: 					FUNCTION | FUNCTION FUNCTIONS

MAIN:	 					T_STARTMAIN "\n" MAINBODY T_ENDMAIN


DECLAREVARS:				T_INT T_IDENTIFIER T_SEMIC 
							| T_INT T_IDENTIFIER T_ASS T_ICONST T_SEMIC 
							| T_INT T_IDENTIFIER T_AGG_OPEN T_INT T_AGG_CLOSE T_SEMIC 
							| T_CHAR T_IDENTIFIER T_SEMIC
							| T_CHAR T_IDENTIFIER T_ASS T_CCONST T_SEMIC 
							| T_CHAR T_IDENTIFIER T_AGG_OPEN T_INT T_AGG_CLOSE T_SEMIC

FUNCTIONBODY:				BLOCKS "\n" T_RETURN T_IDENTIFIER T_SEMIC
							| BLOCKS "\n" T_RETURN T_ICONST T_SEMIC
							| BLOCKS "\n" T_RETURN T_CCONST T_SEMIC
							
MAINBODY:					BLOCKS

BLOCK:						ASSIGNMENT | IFSTATEMENT | WHILELOOP | FORLOOP | SWITCHES | FUNCTIONCALL | PRINT | T_BREAK

BLOCKS:						BLOCK | BLOCKS BLOCK


COMPEXPRESSION:				T_IDENTIFIER T_COMPOP T_IDENTIFIER 
							| T_IDENTIFIER T_COMPOP	 T_ICONST 
							| T_ICONST T_COMPOP	T_ICONST 
							| T_IDENTIFIER T_COMPOP	 _CCONST 
							| T_CCONST T_COMPOP	T_CCONST

LOGICALEXPRESSION:			T_BRA_OPEN COMPEXPRESSION LOGICAL_OPERATOR COMPEXPRESSION T_BRA_CLOSE 
							| T_BRA_OPEN COMPEXPRESSION LOGICAL_OPERATOR LOGICALEXPRESSION T_BRA_CLOSE 
							| T_BRA_OPEN LOGICALEXPRESSION LOGICAL_OPERATOR LOGICALEXPRESSION T_BRA_CLOSE

OPERATION:			 		T_ICONST OPERATOR T_ICONST 
							| T_IDENTIFIER OPERATOR T_IDENTIFIER 
							| T_IDENTIFIER OPERATOR T_ICONST 
							| T_ICONST OPERATOR T_IDENTIFIER 
							| T_BRA_OPEN OPERATION T_BRA_CLOSE
							
OPERATIONS:		 			OPERATION
							| OPERATION OPERATOR T_ICONST 
							| OPERATION OPERATOR T_IDENTIFIER 
							| OPERATION OPERATOR OPERATION 
							| OPERATION OPERATOR OPERATIONS

ASSIGNMENT:					T_IDENTIFIER T_ASS T_ICONST T_SEMIC 
							| T_IDENTIFIER T_ASS T_CCONST T_SEMIC 
							| T_IDENTIFIER T_ASS OPERATIONS T_SEMIC 
							| T_IDENTIFIER T_ASS FUNCTIONCALL T_SEMIC


WHILELOOP: 					T_WHILE LOGICALEXPRESSION "\n" BLOCKS "\n" T_ENDWHILE
							| T_WHILE COMPEXPRESSION "\n" BLOCKS "\n" T_ENDWHILE

FORLOOP:      				T_FOR T_IDENTIFIER T_FOROP T_ICONST T_TO  T_ICONST T_STEP T_ICONST "\n" BLOCKS T_ENDFOR

IFSTATEMENT:				T_IF LOGICALEXPRESSION "\n" T_THEN BLOCKS T_ENDIF 
							| T_IF LOGICALEXPRESSION "\n" T_THEN BLOCKS ELSEIF T_ELSE "\n" BLOCKS T_ENDIF
							
ELSEIF: 					T_ELSEIF LOGICALEXPRESSION "\n" BLOCKS | T_ELSEIF LOGICALEXPRESSION "\n" BLOCKS ELSEIF 

SWITCHES: 					T_SWITCH T_BRA_OPEN T_IDENTIFIER T_BRA_CLOSE "\n" CASES "\n" T_DEFAULT "\n" BLOCKS "\n" T_ENDSWITCH 
							| T_SWITCH T_BRA_OPEN T_IDENTIFIER T_BRA_CLOSE "\n" CASES "\n" T_ENDSWITCH
							
CASE:						T_CASE T_ICONST "\n" BLOCKS | T_CASE T_CCONST "\n" BLOCKS | T_CASE OPERATOR "\n" BLOCKS

CASES:      				CASE | CASES CASE

FUNCTIONCALL:				T_IDENTIFIER T_BRA_OPEN VARIABLES T_BRA_CLOSE T_SEMIC

PRINT:						T_PRINT T_BRA_OPEN T_SCONST T_BRA_CLOSE T_SEMIC 
							| T_PRINT T_BRA_OPEN T_SCONST T_COMMA T_IDENTIFIER T_BRA_CLOSE T_SEMIC

COMMENTS:					T_COMM 




%%



